version: '3.7'
services:
  slackube:
    container_name: slackube
    build:
      context: .
      target: build
    environment:
      - APP_ENV=dev
      - SLACK_TOKEN=${SLACK_TOKEN}
    volumes:
      - ./:/go/src/slackube/
    working_dir: /go/src/slackube/
    entrypoint: /bin/sh
    command: -c "go get github.com/pilu/fresh && fresh"
